name: SlimeEnchanter
author: Jelcoo
description: Craft vanilla enchantment books with SlimeFun
website: https://github.com/Jelcoo/SlimeEnchanter
version: ${project.version}

depend: [Slimefun]
main: me.Jelcoo.slimeenchanter.SlimeEnchanter

api-version: 1.14